monitor = DP-1, highrr, 0x0, 1
monitor = DP-2, highrr, 1920x0, 1

# defining starting workspace for each application

workspace=1,monitor:DP-2
workspace=2,monitor:DP-2
workspace=3,monitor:DP-2
workspace=4,monitor:DP-2
workspace=5,monitor:DP-2
workspace=6,monitor:DP-2
workspace=7,monitor:DP-2
workspace=8,monitor:DP-2
workspace=9,monitor:DP-2

workspace=11,monitor:DP-1
workspace=12,monitor:DP-1
workspace=13,monitor:DP-1
workspace=14,monitor:DP-1
workspace=15,monitor:DP-1
workspace=16,monitor:DP-1
workspace=17,monitor:DP-1
workspace=18,monitor:DP-1
workspace=19,monitor:DP-1

windowrulev2=workspace 1,initialClass:($browser)
windowrulev2=workspace 2,initialClass:(code-url-handler),initialTitle:(Visual Studio Code)
windowrulev2=workspace 3,initialClass:(kitty),initialTitle:(kitty)
windowrulev2=workspace 4,initialClass:(vesktop),initialTitle:(Discord)
windowrulev2=workspace 19,initialTitle:(Spotify Premium)