{
  config,
  lib,
  pkgs,
  ...
}:
lib.mkIf config.desktop.enable {
  home.packages = with pkgs; [
    brave
    easyeffects
    firefox
    font-manager
    gimp
    google-chrome
    gnome-disk-utility
    hyprsunset
    jetbrains.idea-ultimate
    kdePackages.xwaylandvideobridge
    libreoffice
    librewolf
    moonlight-qt
    nautilus
    obsidian
    obs-studio
    openrazer-daemon
    pavucontrol
    polychromatic
    postman
    protonup-qt
    rquickshare
    swww
    themechanger
    tor-browser
    typst
    vesktop
    vivaldi
    vlc
    wineWowPackages.waylandFull
    wireguard-tools
    wireshark-qt
    wl-clicker
    wl-clipboard
    zoom
    zotero
  ];
}
