{
  config,
  lib,
  pkgs,
  ...
}: {
  home.packages = lib.mkIf config.desktop.enable (with pkgs; [
    brave
    firefox
    font-manager
    gimp
    google-chrome
    gnome-disk-utility
    hyprsunset
    jetbrains.idea-ultimate
    kdePackages.xwaylandvideobridge
    libreoffice
    librewolf
    moonlight-qt
    nautilus
    obsidian
    obs-studio
    openrazer-daemon
    pavucontrol
    polychromatic
    postman
    rquickshare
    swww
    themechanger
    typst
    ventoy-full
    vesktop
    vivaldi
    vlc
    wineWowPackages.waylandFull
    wireguard-tools
    wireshark-qt
    wl-clicker
    zenity
    zoom
    zotero
  ]);
}
