fs=yes

#geometry=50%:50%

#autofit-larger=90%x90%

#keep-open=yes

#force-window=immediate

osc=no

osd-font=0xProto Nerd Font
osd-font-size=10
osd-border-size=0
osd-duration=5000
osd-playing-msg='${filename}'

#ontop=yes

profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
gpu-context=wayland

#video-sync=display-resample

#hwdec=auto

screenshot-format=png
screenshot-png-compression=0
screenshot-directory=$HOME/pictures/mpv_screenshots/

#audio-device=alsa/default

#audio-pitch-correction=no

#audio-channels=5.1
#audio-channels=auto

#user-agent="Mozilla/5.0"

#cache=yes
#demuxer-max-bytes=500M
#demuxer-max-back-bytes=100M
#cache-pause=no
#cache-dir=~/.cache/
#cache-on-disk=yes

#slang=en

sub-font='Inter'
sub-font-size=10
sub-ass-force-style=FontName=Inter,FontSize=32
embeddedfonts=no

#alang=fi,en

#sub-codepage=cp1256

#include=/path/to/the/file/you/want/to/include

#[eye-cancer]
#sharpen=5
